# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OTTDMapper
                                 A QGIS plugin
 This plugin adds functionality for generating OpenTTD maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-14
        copyright            : (C) 2023 by Ian Earle
        email                : ian.s.m.earle@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OTTDMapper class from file OTTDMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ottd_mapper import OTTDMapper
    return OTTDMapper(iface)
